# Generated by Django 3.2.9 on 2024-04-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_desc', models.CharField(max_length=250)),
                ('project_repo', models.CharField(max_length=100)),
            ],
        ),
    ]
